spring.application.name=AuctionSystem

# Server Configuration
server.port=8080

# DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/auction_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=never

# Jackson Configuration
spring.jackson.serialization.fail-on-empty-beans=false

# MyBatis Plus Configuration
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.mapper-locations=classpath*:mapper/**/*.xml

# LocalUpdate
app.upload.dir=./uploads
app.upload.base-url=/uploads

# Custom Application Configuration
app.auction.default-extend-minutes=5
app.auction.max-extend-count=3
app.auction.extend-threshold-minutes=5

# Image-related settings
# Compression is triggered when the image size exceeds image.max-size-bytes (in bytes), default is 5MB
image.max-size-bytes=5242880
image.max-width=1024
image.max-height=1024

# Rough maximum file protection on the Controller side (directly reject if too large)
image.max-size-bytes-controller=5242880

# JWT
jwt.secret=56035A954E6AB0FD5E69B7E89C996A22B12D843AC9C6E5245C34461B7C40C2F6
jwt.expiration-seconds=3600
jwt.header=Authorization
jwt.token-prefix=Bearer
jwt.refresh-expiration-days=30

#redis
token.blacklist.store=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache Configuration (memory cache TTL in milliseconds, default 5 minutes)
app.cache.item-ttl-ms=300000

# Order Payment Deadline (hours)
app.pay.deadline-hours=24

# Receipt Directory
app.receipts.dir=receipts

logging.level.org.springframework.security=DEBUG

# OpenAPI/Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Mail Configuration
spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=2784312635@qq.com
spring.mail.password=ruqbefawubusdcib
management.health.mail.enabled=false

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Breach configuration
# For payment breach: credit deduction score | deposit action: FORFEIT | FREEZE | NONE?
app.breach.payment.credit-deduction=10
app.breach.payment.deposit-action=FORFEIT

# For shipping breach: credit deduction score | deposit action: FORFEIT | FREEZE | NONE?
app.breach.shipping.credit-deduction=10
app.breach.shipping.deposit-action=NONE

# Shipping deadline in hours, triggers OverdueShippingScheduler after this time, default is 72 hours.
app.shipping.ship-by-hours=72

# Credit Score Mechanism
app.auction.credit-score.min-to-bid=60
app.auction.credit-score.min-to-list=60

alipay.app-id=9021000162620309
alipay.merchant-private-key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCa2VQqo8uLo1N6otsCEzQ/SHNfJ27BjD2t3cWIKezqUr8Dlf62+RVN0ZDYjD6mvyvygoDONejUR+9YlZR+G/GTzCHv0c+9O7SYqiNiUydJrYrvGra0uBOAQCXa4EvvSHaF0xRS+ucbrRl+N2ah8/Au3ykLg9OQcNFlbMHW4+4hL/P+kJ5opMp5Yw7haq+No4YLIqzgicn4r7NU1wBbmhwQFFqFZkbJH5s6LwwB+WXAu59IaRp8qK5AfmX+ZcyVecGkuQsRQosiIldI1PCD338cIUdCSuzShq30RSqGslZUS3vVdnF6DZJZtZ7cRYAaECVRI4sdEKsoXNyebtTvNic7AgMBAAECggEANMljZMnDiI2b1pGPwSxUwkHreoORwQ8Ss6OHQ/yu085zaUCHvU46EfYfv4JHlUZUL+6HBETiYwNGt1b+cOMLvkt3Qi6u955T2TseptUb7oTneM0NfZvGohC8FtohaKe2J7amFgeMIyYmK52tMgZbWU8fydodk/6xkza4+Y1nzw3m4DBjmglAk7e8CO1aL19Yw9BKx7K9S/Y5KJArWyWLUwsUqtyVwjJ36y9LlATSwf7Xn5U1v+VZTd7UxBj0GFhV2Tsm49zqInFdtxkSOFdwSu+gHxEOPnyraNpGptQzsfLgo5f/MnGnIhwenCAqZlEDGpxmIDEX/OLJP+DRovscAQKBgQDRSIXB27iOlIbpLHRmRW7lHbYNsx7n7qcGKOq12c9dqhrZhvjGYNV/m9ZH3+v+XRaCeXoIuX7gNZH2YdiI2xLnCHJR7QSyBZuUFejI+hTQdLOn2muOU32ePMmOOPrbUDKIozNORjXEmW0p42iysrBoE57DVtuswI7H0rCYxW2uAQKBgQC9aijXC5+3gugui6Mpxg0Ma4/FO2cXFc66aKxurbzIFfEqTC8XEc7DuPCnle4c0VgdNFtxRRTeDzsDSAMpVc/ZKQBOyu8vDEibwKiCgSrNbY0Nqle9YUQ8TucE5dsz8nS0dzmm7WKESrC/Ced8w1ZTpvfCsPXAOBT2qcdQ3xkNOwKBgQC7MQ4KvrgOOAWP7KZUj8hIANJE4LFFLK6SkOiXLbIQCkWnydUcw6JTWJVKhpw0URkALR2dTiWQ7/mVkiE3EBSRN3nhk4n+nYtx4kLr+NvDNI85FOHdVQpoDeEOaCLhJZN9qdQLMDuJlN4SeIi+RZwKC3qXKEqm8zkCvI4ep4CaAQKBgAwVereFaVIWyuM1S1p95RU2w3xMtt31KTQhO2bwNIv7QmB1bcel/i/kW44FdaRnAp0SWwcV5ifohtZFwNXhQJpVEEz2i13QBc3R864nuWhTpd0KUgCl9Ol4Cyr30w00WZetx4LLwC46aZ42bos6FwbNLx8/lN4Hdebqm+mf4gRDAoGAZlntDHmMCEdBV4oz9eFdXXS7xWnMe0Aj7HRyNkOFQjxCGwQNzITwZ3O+SwJCWm5wjf7WTLxl3hbUoaEKzzy3ONOMis1HmrV5vOD8YBAo+nxKwpKQk1oD/4NByfLGq1yATkZhWDao+XBFlzVmb8jWJURySIr/UYUkH8rAfyDbRe4=
alipay.alipay-public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmVBdWeHkWh6t0nXd/wKHicF2RDWKkg8EyIDcL5+vlQrRdtO5UGdzfUsiLfvemnrGkpuB4QLduddMbFhhw+ZJzJP7HyXVfTTKeQA7T+KdPbfS2qTfFcnleIf+U1Yizg47sM5XYFIUjTIRFALC4b9ls9B0x1GVhrriUUpGggC6qdAZOsJQSSy7OSJNtfIkPRmS0gfIDULfKC/VnNTwLEREJzJSdzXe+PyPUFDPcdOtxNAgWDw+vVTX2BNVHqJ1xoN9hh5bio3CkV6HEprslGDU2xGEBU93DVC94Y2WjENjdC1tSDxvMJylAa/akBWUZ6SoRiYfWtUR46olE7kmBri9zQIDAQAB
alipay.gateway-url=https://openapi-sandbox.dl.alipaydev.com/gateway.do
alipay.sign-type=RSA2
alipay.charset=utf-8
app.public-base-url=http://k9947a38.natappfree.cc
alipay.notify-url=${app.public-base-url}/alipay/notify
alipay.return-url=${app.public-base-url}/alipay/return

app.frontend.base-url=http://localhost:3000

