spring.application.name=AuctionSystem

# Server Configuration
server.port=8080

# DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/auction_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=never

# Jackson Configuration
spring.jackson.serialization.fail-on-empty-beans=false

# MyBatis Plus Configuration
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.mapper-locations=classpath*:mapper/**/*.xml

# LocalUpdate
app.upload.dir=./uploads
app.upload.base-url=/uploads

# Custom Application Configuration
app.auction.default-extend-minutes=5
app.auction.max-extend-count=3
app.auction.extend-threshold-minutes=5

# Image-related settings
# Compression is triggered when the image size exceeds image.max-size-bytes (in bytes), default is 5MB
image.max-size-bytes=5242880
image.max-width=1024
image.max-height=1024

# Rough maximum file protection on the Controller side (directly reject if too large)
image.max-size-bytes-controller=5242880

# JWT
jwt.secret=56035A954E6AB0FD5E69B7E89C996A22B12D843AC9C6E5245C34461B7C40C2F6
jwt.expiration-seconds=3600
jwt.header=Authorization
jwt.token-prefix=Bearer
jwt.refresh-expiration-days=30

#redis
token.blacklist.store=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache Configuration (memory cache TTL in milliseconds, default 5 minutes)
app.cache.item-ttl-ms=300000

# Order Payment Deadline (hours)
app.pay.deadline-hours=24

# Receipt Directory
app.receipts.dir=receipts

logging.level.org.springframework.security=DEBUG

# OpenAPI/Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Mail Configuration
spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=2784312635@qq.com
spring.mail.password=ruqbefawubusdcib

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true